# Generated by Django 4.2.2 on 2023-06-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_to', models.CharField(blank=True, max_length=12, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer')], max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.account')),
            ],
        ),
    ]
