# Generated by Django 4.2.2 on 2023-06-29 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_rename_account_id_transaction_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
