# Generated by Django 4.2.2 on 2023-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
