# Generated by Django 4.2.2 on 2023-06-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_alter_customer_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pic',
        ),
    ]
