# Generated by Django 4.2.2 on 2023-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_loan_end_date_alter_loan_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='interest_earned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('matured', 'matured'), ('closed', 'closed'), ('req_stop', 'req_stop')], max_length=50),
        ),
    ]
