# Generated by Django 4.2.2 on 2023-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_alter_fixeddeposit_interest_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
